name: Create Release

on:
  push:
    tags: 
      - 'v*.*.*'

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest] 
        node-version: [14.x]
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'

    - name: Install Yarn
      run: |
        npm install -g yarn
        yarn cache clean --force

    - name: Install 
      run: yarn

    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: yarn build

    - name: Upload file
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        name: ${{ matrix.os }}
        path: |
          build/*latest*.yml
          build/*.exe
          build/*.dmg
          build/*.snap
          build/*.blockmap

    - name: Get Tag Name
      id: extract_tag
      run: |
        echo "tag_name=${GITHUB_REF#refs/tags/}" >> ${GITHUB_OUTPUT}
    
    - name: Extract Changelog In Windows
      id: extract_changelog_windows
      if: matrix.os == 'windows-latest'
      run: |
        $delimiter = '---'
        Get-Content -Path 'CHANGELOG.md' | ForEach-Object {
          if ($_ -eq $delimiter) {
            break
          }
          $_ | Out-File -Append -FilePath 'release_body.md'
        }

    - name: Extract Changelog In Linux & Mac 
      id: extract_changelog_unix
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        # Set the delimiter
        delimiter="---"

        # Read the file and extract the first part
        while IFS= read -r line
        do
            if [[ "$line" == "$delimiter" ]]
            then
                break
            fi
            echo $line >> release_body.md
        done < "CHANGELOG.md"

    - name: Release
      if: ${{ !env.ACT }} && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/*latest*.yml
          build/*.exe
          build/*.dmg
          build/*.snap
          build/*.blockmap
        tag_name: ${{ steps.extract_tag.outputs.tag_name }}
        release_name: Release ${{ steps.extract_tag.outputs.tag_name }}
        body_file: release_body.md
        token: ${{ secrets.GH_TOKEN }}
