name: Create Release

on:
  push:
    tags: 
      - 'v*.*.*'

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest, fedora-latest] 
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build
      run: npm run build
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: |
          build/*latest*.yml
          build/*.exe
          build/*.dmg
          build/*.rpm
          build/*.deb
          build/*.blockmap
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/*latest*.yml
          build/*.exe
          build/*.dmg
          build/*.rpm
          build/*.deb
          build/*.blockmap
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
