name: Create Release

on:
  push:
    tags: 
      - 'v*.*.*'

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest] 
        node-version: [14.x]
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
    - name: Install Yarn
      run: |
        npm install -g yarn
        yarn cache clean --force
    - name: Install 
      run: yarn
    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: yarn build
    - name: Upload file
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        name: ${{ matrix.os }}
        path: |
          build/*latest*.yml
          build/*.exe
          build/*.dmg
          build/*.snap
          build/*.blockmap
    - name: Release
      if: ${{ !env.ACT }} && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/*latest*.yml
          build/*.exe
          build/*.dmg
          build/*.snap
          build/*.blockmap
        tag_name: v0.0.1
        release_name: Release 0.0.1
        body: |
          ## Feature
          - Tcp client.
        token: ${{ secrets.GH_TOKEN }}
