name: Docs Publish

on:
  push:
    branches:
        - '*'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}